config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'	

  resources :users do
    member do
      get :following, :followers
    end
  end
  match '/signup',	to: 'users#new',	via: 'get'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',	to: 'sessions#new',	via: 'get'
  match '/signout',	to: 'sessions#destroy',	via: 'delete'

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  delete 'relationships'  => 'relationships#destroy'

  resources :movies, only: [:index, :show]
  post '/own' => 'movies#own'
  post '/unown' => 'movies#unown'
  get '/my_movies' => 'movies#owned'
  get '/now_playing_movies' => 'movies#now_playing'
  get '/upcoming_movies' => 'movies#upcoming'
  get '/popular_movies' => 'movies#popular'
  get '/top_rated_movies' => 'movies#top_rated'  

  resources :lists
  post '/remove_from_list' => 'lists#remove_movie'
  post '/add_to_list' => 'lists#add_movie'
  post '/shares' => 'lists#share'
  resources :tv, only: [:index, :show]
  resources :collections, only: [:index, :show]
  resources :person, only: [:index, :show]
  resources :company, only: [:index, :show]
  resources :genres, only: [:index, :show]

  post 'search' => "search#index"

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  has_many :items, dependent: :destroy
  has_many :movies, through: :items
  has_many :shares, dependent: :destroy
  has_many :users, through: :shares

  validates :name, presence: true
  validates :user_id, presence: true

  def share_attributes=(share_attributes)
    share_attributes.each do |attributes|
      share.build(attributes)
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user,   only: [:edit, :update]

  helper :movie

  def index
    @shares = current_user.shares.page params[:page]
  end
  
  def show
    @share = Share.find_by(list_id: params[:id], user_id: current_user.id)
    if @share.nil?
      flash[:warning] = "You do not have access to this list"
      redirect_to lists_url
    else
      @list = @share.list
      @movies = initialize_grid(@share.list.movies.select("DISTINCT movies.*").joins(:classifications), include: [:genres], order: 'movies.title' , per_page: 10)
      @configuration = Mytmdb.new.configuration
    end
  end

  def destroy
    List.find(params[:id]).destroy
    flash[:success] = "List deleted."
    redirect_to lists_url
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      @list.shares.build(writable: true, user_id: @list.user_id)
      if @list.save
        flash[:success] = "List Saved."
        redirect_to @list
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(list_params)
      flash[:success] = "List updated"
      redirect_to @list
    else
      render 'edit'
    end
  end

  def remove_movie
    if Item.find_by(movie_id: params[:movie_id], list_id: params[:list_id]).destroy
      flash[:success] = "Movie has been removed from this list."
    end
    redirect_to list_path(params[:list_id])
  end
  
  def add_movie
    @mb = MovieBuilder.new
    @item = Item.new(list_id: params[:list_id], movie_id: @mb.set_imdb_id(params[:movie_id]).create.id)
    if Item.find_by(movie_id: @item.movie_id, list_id: @item.list_id).present?
      flash[:warning] = "Movie already in List"
    elsif @item.save
      flash[:success] = "Movie added to List"
    end
    redirect_to list_path(params[:list_id])
  end

  def share
    @share = Share.new(share_params)
    if Share.find_by(user_id: @share.user_id, list_id: @share.list_id).present?
      flash[:warning] = "List already shared to User"
    elsif @share.save
      flash[:success] = "List shared."
    else
      flash[:error] = "Error occured. Please try again."
    end
    redirect_to list_path(@share.list_id)
  end

  private
  
    def list_params
      params.require(:list).permit(:name, :user_id)
    end

    def share_params
      params.require(:share).permit(:user_id, :list_id, :writable)
    end

    def correct_user
      if List.find_by(id: params[:id], user_id: current_user.id).nil?
        flash[:warning] = "You do not have access to modify this list"
        redirect_to lists_path
      end
    end
end

app/helpers/lists_helper.rb
module ListsHelper
  def list_owner_name list
    if current_user == list.user 
      "Your List"
    else
      list.user.name 
    end
  end
end

app/views/lists/_add_form.html.erb
<% if current_user.writable_lists.any? %>
  <div class="lists">
    <%= form_tag '/add_to_list' do %>
      <%= select_tag "list_id", options_from_collection_for_select(current_user.writable_lists, "id", "name") %>
      <%= hidden_field_tag 'movie_id', movie_id %>
      <%= submit_tag "Add to List", class: "btn btn-medium" %>
    <% end %>
  </div>
<% end %>

app/views/lists/_fields.html.erb
<%= render 'shared/error_messages', object: f.object%>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.hidden_field :user_id, :value => current_user.id %>

app/views/lists/_list.html.erb
<% if @list.movies.any? %>
  <h3>Movies (<%= @list.movies.count %>)</h3>
  <%= render 'movies/grid' %>
<% end %>

app/views/lists/_remove_form.html.erb
<%= form_tag '/remove_from_list' do %>
  <div><%= hidden_field_tag 'list_id', list_id %></div>
  <div><%= hidden_field_tag 'movie_id', movie_id %></div>
  <%= submit_tag "Remove From List", class: "btn btn-medium" %>
<% end %>

app/views/lists/_share_form.html.erb
 <div class='share'>
  <% if @share.writable && current_user.sharable_users(@list.id).any? %>
    <%= form_for(@list.shares.build(list_id: @list.id)) do |f| %>
      <%= f.hidden_field :list_id, { :value => @list.id } %>

      <% followers = current_user.followers.map { |user| [user.name, user.id] } %>
      <%= f.select(:user_id, options_for_select(followers)) %>

      <%= f.label :writable, "User Can Edit List" %>
      <%= f.check_box :writable %>

      <%= f.submit "Share List", class: "btn btn-medium btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/lists/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update <%= @list.name %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@list) do |f| %>
       <%= render 'fields', f: f %> 
       <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/lists/index.html.erb
<% provide(:title, 'Lists') %>
<h1>Lists</h1>
<%= render "search/back_to_results" %>
<%= link_to "New List", new_list_path, class: "btn btn-large btn-primary" %>

<%= paginate @shares %>

<ul class="users">
  <% @shares.each do |s| %>
    <li><%= link_to s.list.name, s.list %> - <%= link_to list_owner_name(s.list), s.list.user %>
 (<%= s.list.movies.count %>)
      <% if s.list.user == current_user %>
       | <%= link_to "Change Name", edit_list_path(s.list) %> | <%= link_to "Delete", s.list, method: :delete, data: { confirm: "Are you sure you want to delete #{s.list.name}" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= paginate @shares %>

app/views/lists/new.html.erb
<% provide(:title, 'Create List') %>
<h1>New List</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@list) do |f| %>
      <%= render  'fields', f: f %>
      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<% provide(:title, @list.name) %>
<%= render "search/back_to_results" %>
<h3><%= @list.name %></h3>
<%= render "share_form" %>
<h4><%= list_owner_name(@list) %></h4>

<%= render 'list' %>