config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get '/contact' => 'static_pages#contact'
  get '/about' => 'static_pages#about'
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'	

  resources :users do
    member do
      get :following, :followers
    end
  end
  match '/signup',	to: 'users#new',	via: 'get'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',	to: 'sessions#new',	via: 'get'
  match '/signout',	to: 'sessions#destroy',	via: 'delete'

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  delete 'relationships'  => 'relationships#destroy'

  resources :movies, only: [:index, :show]
  post '/own' => 'movies#own'
  post '/unown' => 'movies#unown'
  get '/my_movies' => 'movies#owned'
  get '/now_playing_movies' => 'movies#now_playing'
  get '/upcoming_movies' => 'movies#upcoming'
  get '/popular_movies' => 'movies#popular'
  get '/top_rated_movies' => 'movies#top_rated'  

  resources :lists
  post '/remove_from_list' => 'lists#remove_movie'
  post '/add_to_list' => 'lists#add_movie'
  post '/shares' => 'lists#share'
  resources :tv, only: [:index, :show]
  resources :collections, only: [:index, :show]
  resources :person, only: [:index, :show]
  resources :company, only: [:index, :show]
  resources :genres, only: [:index, :show]

  post 'search' => "search#index"

end

app/models/search.rb
class Search
  def initialize type, value
    @type = type
    @value = value
  end

  def results
    SearchFactory.build(@type).find(@value)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @results = Search.new(params[:type], params[:value]).results
    if @results.any?
      @configuration = @results.first.configuration
      session[:search_type] = params[:type]
      session[:search_value] = params[:value]
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def render_results 
    render SEARCH_LIST[0][params[:type].to_i][:view]   
  end

  def search_has_been_performed?
    session[:search_type].present? && session[:search_value].present?
  end

  def get_search_type
    session[:search_type] if session[:search_type].present?
  end

  def get_search_value
    session[:search_value] if session[:search_value].present?
  end
end

app/views/search/_back_to_results.html.erb
<% if search_has_been_performed? %>
  <%= form_tag("/search") do %>
    <%= hidden_field_tag(:type, get_search_type) %>
    <%= hidden_field_tag(:value, get_search_value) %>
    <%= submit_tag("Back To Search Results", :class => "btn btn-medium") %>
  <% end %>
<% end %>

app/views/search/_movie_results.html.erb
<table class="table table-bordered table-striped table-hover">
  <% @results.each do |movie| %>
    <tr>
      <td style="width:15%">
        <%= link_to movie_path(movie.details.id) do %>
        <%= image_tag("#{@configuration.base_url}w154#{movie.details.poster_path}") if movie.details.poster_path %>
        <% end %>
      </td>
      <td>
        <%= link_to movie.details.title, movie_path(movie.details.id) %> (<%= movie.details.release_date %>) <br />
        <%= render 'movies/own_form', id: movie.details.id, title: movie.details.title  if signed_in? %>
        <%= render 'lists/add_form', movie_id: movie.details.id  %>
        <% if movie.crew.any? %>
          Directors: <% movie.crew.each do |crew| %> <% if crew['department'] == 'Directing' %> <%= link_to crew['name'], person_path(crew['id']) %> <% end %><% end %><br />
        <% end %>
        <% if movie.cast.any? %>
          Starring: <% movie.cast.first(3).each do |cast| %> <%= link_to cast['name'], person_path(cast['id']) %> | <% end %>
       <% end %><br />
      </td>
    </tr>
  <% end %>
</table>

app/views/search/_person_results.html.erb
<table class="table table-bordered table-striped table-hover">
  <% @results.each do |person| %>
    <tr>
      <td style="width:15%">
        <%= link_to person_path(person.details.id) do %>
        <%= image_tag("#{@configuration.base_url}w154#{person.details.profile_path}") if person.details.profile_path %>
	<% end %>
      </td>
      <td>
        <%= link_to person.details.name, person_path(person.details.id) %> ( <%= person.details.birthday %>
        <% if person.details.deathday.present? %>
          - <%= person.details.deathday %>
        <% end %>)<br />
        <% if person.details.place_of_birth.present? %>
          Place of Birth: <%= person.details.place_of_birth %>
        <% end %><br /><br />
	<% if person.movie_credits.cast.any? %>
          Movies: |<% person.movie_credits.cast.each do |movie| %>
            <%= link_to movie['title'], movie_path(movie['id']) %> |
          <% end %>
	<% end %><br/><br/>
	<% if person.tv_credits.cast.any? %>
          TV: |<% person.tv_credits.cast.each do |tv| %>
            <%= link_to tv['name'], tv_path(tv['id']) %> |
          <% end %>
	<% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/search/_tv_results.html.erb
<table class="table table-bordered table-striped table-hover">
  <% @results.each do |tv| %>
    <tr>
      <td style="width:15%">
        <%= link_to tv_path(tv.details.id) do %>
        <%= image_tag("#{@configuration.base_url}w154#{tv.details.poster_path}") if tv.details.poster_path %>
        <% end %>
      </td>
      <td>
        <%= link_to tv.details.name, tv_path(tv.details.id) %> ( <%= tv.details.first_air_date %> 
        <% if tv.details.last_air_date.present? %>
         - <%= tv.details.last_air_date %><% end %> ) <br /><br />
        <% if tv.details.created_by.any? %>
	  Creators: <% tv.details.created_by.each do |creator| %> 
            <%= link_to creator.name, person_path(creator.id) %>
          <% end %><br />
        <% end %>
	Starring: | <% tv.cast.each do |cast| %> 
          <%= link_to cast.name, person_path(cast.id) %> |
        <% end %><br />
      </td>
    </tr>
  <% end %>
</table>

app/views/search/index.html.erb
<h3>Search Results</h3>
<% if @results.any? %>
  <%= render_results %>
<% else %>
  <p>Sorry, No Results. Please refine your search to be more specific.</p>
<% end %>